TDM.Core/TDM/Server/Web/Controllers/AuthController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Mvc;
using Supermodel.Persistence.Repository;
using Supermodel.Persistence.UnitOfWork;
using Supermodel.Presentation.Mvc.Auth;
using Supermodel.Presentation.Mvc.Bootstrap4.Models;
using Supermodel.Presentation.Mvc.Controllers.Mvc;

namespace Web.Controllers;

public class AuthController : SimpleAuthController<Bs4.LoginMvcModel>
{
    protected override async Task<List<Claim>> AuthenticateAndGetClaimsAsync(string username, string password)
    {
        await using(new UnitOfWork<DataContext>(ReadOnly.Yes))
        {
            var repo = LinqRepoFactory.Create<TDMUser>();
            var lowerCaseUsername =  username.ToLower();
            var user = repo.Items.SingleOrDefault(u => u.Username.ToLower() == lowerCaseUsername);
                
            if (user != null && user.PasswordEquals(password))
            {
                var claims = AuthClaimsHelper.CreateNewClaimsListWithIdAndLabel(user.Id, $"{user.FirstName} {user.LastName}");
                //claims.Add(new Claim(ClaimTypes.Role, "Adder", ClaimValueTypes.String));
                return claims;

            }
            else
            {
                return new List<Claim>();
            }
        }
    }

    protected override IActionResult RedirectToHomeScreen()
    {
        return RedirectToAction("Index", "Home");
    }
}

TDM.Core/TDM/Server/Web/Controllers/InlineToDoListController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Supermodel.Presentation.Mvc.Auth;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using Supermodel.Presentation.Mvc.Extensions.Gateway;
using Web.ViewModels;

namespace Web.Controllers;

[Authorize]
public class InlineToDoListController : EnhancedCRUDController<ToDoList, ToDoListMvcModel, ToDoListSearchMvcModel, DataContext>
{
    #region Overrides
    protected override IQueryable<ToDoList> GetItems()
    {
        var currentUserId = UserHelper.GetCurrentUserId();
        return base.GetItems().Where(x => x.ListOwnerId == currentUserId);
    }
    protected override Task<IActionResult> AfterCreateAsync(long id, ToDoList entityItem, ToDoListMvcModel mvcModelItem)
    {
        var listOwnerId = UserHelper.GetCurrentUserId();
        if (listOwnerId == null) throw new UnauthorizedAccessException();
        entityItem.ListOwnerId = listOwnerId.Value;
        TempData.Super().NextPageModalMessage = "To Do List Created Successfully!";
        return Task.FromResult(StayOnDetailScreen(entityItem.Id));
    }
    protected override IQueryable<ToDoList> ApplySearchBy(IQueryable<ToDoList> items, ToDoListSearchMvcModel searchBy)
    {
        items = base.ApplySearchBy(items, searchBy);
        var searchTerm = searchBy.SearchTerm.Value;
        if (!string.IsNullOrEmpty(searchTerm)) items = items.Where(l => l.Name.Contains(searchTerm) || l.ToDoItems.Any(i => i.Name.Contains(searchTerm)));
        return items;
    }
    #endregion
}

TDM.Core/TDM/Server/Web/Controllers/TDMUserUpdatePasswordController.cs
using System;
using System.Threading.Tasks;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Supermodel.Presentation.Mvc.Auth;
using Supermodel.Presentation.Mvc.Controllers;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using Supermodel.Presentation.Mvc.Extensions.Gateway;
using Web.ViewModels;

namespace Web.Controllers;

[Authorize]
public class TDMUserUpdatePasswordController : CRUDController<TDMUser, TDMUserUpdatePasswordMvcModel, DataContext>
{
    #region Overrides
    public override Task<IActionResult> Detail(long id, HttpGet ignore)
    {
        var userId = UserHelper.GetCurrentUserId();
        if (userId == null) throw new UnauthorizedAccessException();
        return base.Detail(id, ignore);
    }
    public override async Task<IActionResult> Detail(long id, bool? isInline, HttpPut ignore)
    {
        var mvcModelItem = new TDMUserUpdatePasswordMvcModel();
        await TryUpdateModelAsync(mvcModelItem);

        //because we are in Authorize header, current user should not be null
        var currentUser = await UserHelper.GetCurrentUserAsync<TDMUser, DataContext>();
        if (currentUser == null) throw new Exception("currentUser == null: This should never happen");
        if (currentUser.Id != id || !currentUser.PasswordEquals(mvcModelItem.OldPassword.Value))
        {
            TempData.Super().NextPageModalMessage = "Incorrect Old Password!";
            return RedirectToAction(nameof(Detail), new { id });
        }
        return await base.Detail(currentUser.Id, isInline, ignore);
    }

    protected override Task<IActionResult> AfterUpdateAsync(long id, TDMUser entityItem, TDMUserUpdatePasswordMvcModel mvcModelItem)
    {
        TempData.Super().NextPageModalMessage = "Password Updated Successfully!";
        return Task.FromResult((IActionResult)RedirectToAction(nameof(Detail), new { id } ));
    }
    #endregion
        
    #region Disabled Action Methods
    public override Task<IActionResult> List() { throw new InvalidOperationException(); }
    public override Task<IActionResult> Detail(long id, HttpDelete ignore) { throw new InvalidOperationException(); }
    public override Task<IActionResult> Detail(long id, bool? isInline, HttpPost ignore) { throw new InvalidOperationException(); }
    public override Task<IActionResult> BinaryFile(long id, string pn, HttpDelete ignore) { throw new InvalidOperationException(); }
    public override Task<IActionResult> BinaryFile(long id, string pn, HttpGet ignore) { throw new InvalidOperationException(); }
    #endregion
}

TDM.Core/TDM/Server/Web/Controllers/ToDoListController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Supermodel.Presentation.Mvc.Auth;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using Supermodel.Presentation.Mvc.Extensions.Gateway;
using Web.ViewModels;

namespace Web.Controllers;

[Authorize]
public class ToDoListController : EnhancedCRUDController<ToDoList, ToDoListMvcModel, ToDoListSearchMvcModel, DataContext>
{
    #region Overrides
    protected override IQueryable<ToDoList> GetItems()
    {
        var currentUserId = UserHelper.GetCurrentUserId();
        return base.GetItems().Where(x => x.ListOwnerId == currentUserId);
    }
    protected override Task<IActionResult> AfterCreateAsync(long id, ToDoList entityItem, ToDoListMvcModel mvcModelItem)
    {
        var listOwnerId = UserHelper.GetCurrentUserId();
        if (listOwnerId == null) throw new UnauthorizedAccessException();
        entityItem.ListOwnerId = listOwnerId.Value;
        TempData.Super().NextPageModalMessage = "To Do List Created Successfully!";
        return Task.FromResult(StayOnDetailScreen(entityItem.Id));
    }
    protected override IQueryable<ToDoList> ApplySearchBy(IQueryable<ToDoList> items, ToDoListSearchMvcModel searchBy)
    {
        items = base.ApplySearchBy(items, searchBy);
        var searchTerm = searchBy.SearchTerm.Value;
        if (!string.IsNullOrEmpty(searchTerm)) items = items.Where(l => l.Name.Contains(searchTerm) || l.ToDoItems.Any(i => i.Name.Contains(searchTerm)));
        return items;
    }
    #endregion
}

TDM.Core/TDM/Server/Web/Views/Shared/_EmptyLayout.cshtml
<!doctype html>
<html lang="en">
<head super-bs4-add-meta-and-links="true">
    <title>TDM.Core</title>
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body super-bs4-add-scripts="true" style="margin: 10px">
    @RenderBody()
</body>
</html>

TDM.Core/TDM/Server/Web/Views/Shared/_EmptyModalLayout.cshtml
@{ Layout = "_EmptyLayout.cshtml"; }

<div id="dialog" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                @RenderBody()
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        $('#dialog').modal({backdrop: 'static', keyboard: false});
    });
</script>

TDM.Core/TDM/Server/Web/Views/Shared/_MasterLayout.cshtml
@using Supermodel.Presentation.Mvc.Context

@{ 
    Layout = "_EmptyLayout"; 
}

<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu Group
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-controller="ToDoList" asp-action="List" asp-route-smTake="25">My To Do Lists</a>
                    <a class="dropdown-item" asp-controller="InlineToDoList" asp-action="List" asp-route-smTake="25">My To Do Lists Inline</a>
                </div>
            </li>
        </ul>
        <ul class="nav-item navbar-nav navbar-right">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Welcome, @RequestHttpContext.CurrentUserLabel
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-controller="TDMUserUpdatePassword" asp-action="Detail" asp-route-id="@RequestHttpContext.CurrentUserId">Change Password</a>
                    <a class="dropdown-item" asp-controller="Auth" asp-action="LogOut">Sign Out</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<br/>
<div id="body">
    @RenderBody()
</div>