XXYXX.Core/XXYXX/XXYXX/Server/WebMVC/Models/XXYXXUser.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Domain.Entities;
using Supermodel.DataAnnotations.Attributes;
using Supermodel.DataAnnotations.Validations;
using Supermodel.Presentation.Mvc.Bootstrap4.Models;
using Supermodel.Presentation.Mvc.Models.Api;
using Supermodel.ReflectionMapper;

namespace WebMVC.Models
{
    public class XXYXXUserUpdatePasswordApiModel : ApiModelForEntity<XXYXXUser>
    {
        #region Overrides
        public override Task<T> MapToCustomAsync<T>(T other)
        {
            var user = CastToEntity(other);
            user.Password = NewPassword;
            return base.MapToCustomAsync(other);
        }
        public override Task<ValidationResultList> ValidateAsync(ValidationContext validationContext)
        {
            //we don't want to the domain-level validation to be called here (which called by the base method) because we don't fill that object completely
            var vr = new ValidationResultList();
            return Task.FromResult(vr);
        }
        #endregion
        
        #region Properties
        [Required, NotRMapped] public string OldPassword { get; set; } = "";
        [Required, NotRMapped] public string NewPassword { get; set; } = "";
        #endregion
    }    
    
    public class XXYXXUserUpdatePasswordMvcModel : Bs4.MvcModelForEntity<XXYXXUser>
    {
        #region Overrides
        public override string Label => "N/A";
        public override Task<T> MapToCustomAsync<T>(T other)
        {
            var user = CastToEntity(other);
            user.Password = NewPassword.Value;
            return base.MapToCustomAsync(other);
        }
        public override Task<ValidationResultList> ValidateAsync(ValidationContext validationContext)
        {
            //we don't want to the domain-level validation to be called here (which called by the base method) because we don't fill that object completely
            var vr = new ValidationResultList();
            return Task.FromResult(vr);
        }
        #endregion

        #region Properties
        [Required, NotRMapped] 
        public Bs4.PasswordTextBoxMvcModel OldPassword { get; set; } = new Bs4.PasswordTextBoxMvcModel { PlaceholderBehavior = Bs4.PasswordTextBoxMvcModel.PlaceholderBehaviorEnum.ForceNoPlaceholder };

        [Required, NotRMapped, MustEqualTo(nameof(ConfirmPassword), ErrorMessage = "Passwords do not match")]
        public Bs4.PasswordTextBoxMvcModel NewPassword { get; set; } = new Bs4.PasswordTextBoxMvcModel { PlaceholderBehavior = Bs4.PasswordTextBoxMvcModel.PlaceholderBehaviorEnum.ForceNoPlaceholder };

        [Required, NotRMapped, MustEqualTo(nameof(NewPassword), ErrorMessage = "Passwords do not match")]
        public Bs4.PasswordTextBoxMvcModel ConfirmPassword { get; set; } = new Bs4.PasswordTextBoxMvcModel { PlaceholderBehavior = Bs4.PasswordTextBoxMvcModel.PlaceholderBehaviorEnum.ForceNoPlaceholder };
        #endregion
    }
}

XXYXX.Core/XXYXX/XXYXX/Server/WebMVC/Controllers/AuthController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Supermodel.Persistence.Repository;
using Supermodel.Persistence.UnitOfWork;
using Supermodel.Presentation.Mvc.Auth;
using Supermodel.Presentation.Mvc.Bootstrap4.Models;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using Supermodel.Presentation.Mvc.Extensions;

namespace WebMVC.Controllers
{
    public class AuthController : SimpleAuthController<Bs4.LoginMvcModel>
    {
        #region Overrides
        protected override async Task<List<Claim>> AuthenticateAndGetClaimsAsync(string username, string password)
        {
            await using(new UnitOfWork<DataContext>(ReadOnly.Yes))
            {
                var lowercaseUsername = username.ToLower();
                var user = await LinqRepoFactory.Create<XXYXXUser>().Items.SingleOrDefaultAsync(x => x.Username.ToLower() == lowercaseUsername);

                if (user != null && user.PasswordEquals(password))
                {
                    var claims = AuthClaimsHelper.CreateNewClaimsListWithIdAndLabel(user.Id, $"{user.FirstName} {user.LastName}");

                    //Add claims for the specific permissions following the example below
                    //if (user.Admin) claims.Add(new Claim(ClaimTypes.Role, XXYXXUser.AdminRole, ClaimValueTypes.String));
                    
                    return claims;
                }
                else
                {
                    return new List<Claim>();
                }
            }        
        }
        protected override IActionResult RedirectToHomeScreen()
        {
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).RemoveControllerSuffix());
        }
        #endregion
    }
}

XXYXX.Core/XXYXX/XXYXX/Server/WebMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebMVC.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

XXYXX.Core/XXYXX/XXYXX/Server/WebMVC/Controllers/XXYXXUserUpdatePasswordController.cs
using System;
using System.Threading.Tasks;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Supermodel.Presentation.Mvc.Auth;
using Supermodel.Presentation.Mvc.Controllers;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using Supermodel.Presentation.Mvc.Extensions.Gateway;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    [Authorize]
    public class XXYXXUserUpdatePasswordController : CRUDController<XXYXXUser, XXYXXUserUpdatePasswordMvcModel, DataContext>
    {
        #region Overrides
        public override Task<IActionResult> Detail(long id, HttpGet ignore)
        {
            var userId = UserHelper.GetCurrentUserId();
            if (userId == null) throw new UnauthorizedAccessException();
            return base.Detail(id, ignore);
        }
        public override async Task<IActionResult> Detail(long id, bool? isInline, HttpPut ignore)
        {
            var mvcModelItem = new XXYXXUserUpdatePasswordMvcModel();
            await TryUpdateModelAsync(mvcModelItem);
            var user = await UserHelper.GetCurrentUserAsync<XXYXXUser, DataContext>();
            if (user == null) throw new UnauthorizedAccessException();
            if (user.Id != id || !user.PasswordEquals(mvcModelItem.OldPassword.Value))
            {
                TempData.Super().NextPageModalMessage = "Incorrect Old Password!";
                return RedirectToAction(nameof(Detail), new { id });
            }
            return await base.Detail(user.Id, isInline, ignore);
        }

        protected override Task<IActionResult> AfterUpdateAsync(long id, XXYXXUser entityItem, XXYXXUserUpdatePasswordMvcModel mvcModelItem)
        {
            TempData.Super().NextPageModalMessage = "Password Updated Successfully!";
            return Task.FromResult((IActionResult)RedirectToAction(nameof(Detail), new { id } ));
        }

        #endregion
        
        #region Disabled Action Methods
        public override Task<IActionResult> List() { throw new InvalidOperationException(); }
        public override Task<IActionResult> Detail(long id, HttpDelete ignore) { throw new InvalidOperationException(); }
        public override Task<IActionResult> Detail(long id, bool? isInline, HttpPost ignore) { throw new InvalidOperationException(); }
        public override Task<IActionResult> BinaryFile(long id, string pn, HttpDelete ignore) { throw new InvalidOperationException(); }
        public override Task<IActionResult> BinaryFile(long id, string pn, HttpGet ignore) { throw new InvalidOperationException(); }
        #endregion
    }
}

XXYXX.Core/XXYXX/XXYXX/Server/WebMVC/Views/Shared/_EmptyLayout.cshtml
<!doctype html>
<html lang="en">
<head super-bs4-d3-add-meta-and-links>
    <title>XXYXX</title>
    <link type="image/x-icon" rel="shortcut icon" href="/images/favicon.ico" />
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body super-bs4-d3-add-scripts>
    <script type="text/javascript" src="~/js/site.js"></script>
    @RenderBody()
</body>
</html>

XXYXX.Core/XXYXX/XXYXX/Server/WebMVC/Views/Shared/_EmptyModalLayout.cshtml
@{ Layout = "_EmptyLayout.cshtml"; }

<div id="dialog" class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="background-color: SkyBlue;">
            <div class="modal-body">
                @RenderBody()
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('#dialog').modal({ backdrop: 'static', keyboard: false });
    });
</script>

XXYXX.Core/XXYXX/XXYXX/Server/WebMVC/Views/Shared/_MasterLayout.cshtml
@{
    Layout = "_EmptyLayout";
}
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a href="#" class="dropdown-item">Dropdown Item 1</a>
                    <a href="#" class="dropdown-item">Dropdown Item 2</a>
                    <a href="#" class="dropdown-item">Dropdown Item 3</a>
                </div>
            </li>
        </ul>
        <ul class="nav-item navbar-nav navbar-right">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Welcome, @RequestHttpContext.CurrentUserLabel
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-controller="XXYXXUserUpdatePassword" asp-action="Detail" asp-route-id="@RequestHttpContext.CurrentUserId">Change Password</a>
                    <a class="dropdown-item" asp-controller="Auth" asp-action="LogOut">Sign Out</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<br />
<div id="body">
    @RenderBody()
</div>

XXYXX.Core/XXYXX/XXYXX/Server/WebMVC/Views/XXYXXUserUpdatePassword/Detail.cshtml
@model XXYXXUserUpdatePasswordMvcModel

<super-bs4-crud-edit page-title="Update Password" skip-back-button="true" />